# Generated by Django 3.2 on 2021-04-28 15:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Раздел')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, unique=True, verbose_name='Заголовок статьи')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание статьи')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция в списке')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['position'],
            },
        ),
    ]
